# Generated by Django 5.2.6 on 2025-09-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
