# Generated by Django 5.2.6 on 2025-09-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_route_latitude_route_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
